services:
  - type: web
    name: cleantrust-demo
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r cleantrust_app/requirements.txt
    startCommand: bash -lc "cd cleantrust_app && uvicorn app:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: CLEANLAB_TLM_API_KEY
        sync: false
      - key: S2_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.9
