services:
  - type: web
    name: cleantrust-demo
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker -w 2 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: CLEANLAB_TLM_API_KEY
        sync: false
      - key: S2_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.9
